#ifndef COMPILER_H
#define COMPILER_H

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "token.h"
#include "bytecode.h"

/**
 * Structure to track compilation state
 */
typedef struct s_compiler {
    t_token* current;       // current token
    t_token* previous;      // previous token (to retrieve values)
    t_bytecode* code;       // bytecode being generated
    int had_error;          // error indicator
} t_compiler;

/**
 * Compiler: Tokens → Bytecode
 * 
 * The compiler transforms a list of tokens into executable bytecode.
 * It traverses the tokens and generates the corresponding instructions.
 */

/**
 * Expression compilation (precedence chain, bottom-up)
 */
void compile_primary(t_compiler* compiler);
void compile_factor(t_compiler* compiler);
void compile_term(t_compiler* compiler);
void compile_comparison(t_compiler* compiler);
void compile_equality(t_compiler* compiler);
void compile_expression(t_compiler* compiler);

/**
 * Statement compilation
 */
void compile_let_statement(t_compiler* compiler);
void compile_print_statement(t_compiler* compiler);
void compile_if_statement(t_compiler* compiler);
void compile_while_statement(t_compiler* compiler);
void compile_block(t_compiler* compiler);
void compile_statement(t_compiler* compiler);

/**
 * Compiles a list of tokens into bytecode
 * Returns the generated bytecode
 */
t_bytecode* compile(t_token_list* tokens);

#endif
